import assert from "node:assert/strict";
import test from "node:test";

import {
  DEFAULT_POLICY,
  countPhysicalLines,
  evaluateMutation,
  formatNudge,
  isEligible,
} from "../src/policy.ts";

const lines = (count: number, ending = "\n") => Array.from({ length: count }, (_, index) => `line ${index}`).join(ending);
const policy = { ...DEFAULT_POLICY, projectRoot: "/project", maxLines: 3, significantGrowthLines: 2 };

test("nudge reports size and net growth without demanding numeric file chopping", () => {
  assert.equal(
    formatNudge(1200, 1000),
    "Size nudge: this eligible file is now 1200 physical lines (soft maximum 1000). Consider a cohesive extraction only if the new behavior has a clear local boundary; do not split solely to reach a number or refactor unrelated legacy code.",
  );
  assert.equal(
    formatNudge(1200, 1000, 175),
    "Size nudge: this eligible file is now 1200 physical lines (soft maximum 1000; net growth +175). Consider a cohesive extraction only if the new behavior has a clear local boundary; do not split solely to reach a number or refactor unrelated legacy code.",
  );
});

test("physical lines handle empty, trailing newline, CRLF, blanks, and BOM", () => {
  assert.equal(countPhysicalLines(""), 0);
  assert.equal(countPhysicalLines("one"), 1);
  assert.equal(countPhysicalLines("one\n"), 1);
  assert.equal(countPhysicalLines("one\r\ntwo\r\n"), 2);
  assert.equal(countPhysicalLines("\n\n"), 2);
  assert.equal(countPhysicalLines("\uFEFF"), 0);
  assert.equal(countPhysicalLines("\uFEFFone\n"), 1);
});

test("the three triggers have exact boundaries and ignore shrink and small growth", () => {
  assert.equal(evaluateMutation({ path: "/project/new.ts", before: undefined, after: lines(3), policy }), undefined);
  assert.equal(evaluateMutation({ path: "/project/new.ts", before: undefined, after: lines(4), policy }), formatNudge(4, 3));
  assert.equal(evaluateMutation({ path: "/project/a.ts", before: lines(3), after: lines(4), policy }), formatNudge(4, 3, 1));
  assert.equal(evaluateMutation({ path: "/project/a.ts", before: lines(4), after: lines(5), policy }), undefined);
  assert.equal(evaluateMutation({ path: "/project/a.ts", before: lines(4), after: lines(6), policy }), formatNudge(6, 3, 2));
  assert.equal(evaluateMutation({ path: "/project/a.ts", before: lines(6), after: lines(4), policy }), undefined);
});

test("include wins exclusions, names, paths, binary, and generated markers", () => {
  const content = `// Code generated by x. DO NOT EDIT.\n${lines(4)}`;
  const overridden = { ...policy, include: ["vendor/**"], exclude: ["**/*.ts"] };
  assert.equal(isEligible("/project/vendor/package-lock.json", `${content}\0`, overridden), true);
  assert.equal(evaluateMutation({ path: "/project/vendor/package-lock.json", before: undefined, after: `${content}\0`, policy: overridden }), formatNudge(5, 3));
});

test("explicit excludes precede defaults and unknown text remains eligible", () => {
  assert.equal(isEligible("/project/src/code.ts", lines(4), { ...policy, exclude: ["src/**"] }), false);
  assert.equal(isEligible("src/code.ts", lines(4), { ...policy, exclude: ["src/**"] }), false);
  assert.equal(isEligible("/project/docs/migrations/schema.yaml", lines(4), policy), true);
  assert.equal(isEligible("/tmp/build/project/src/code.ts", lines(4), { ...policy, projectRoot: "/tmp/build/project" }), true);
  assert.equal(isEligible("Carthage/Build/generated.swift", lines(4), policy), false);
  assert.equal(isEligible("/project/fixtures/testdata/example.json", lines(4), policy), true);
  assert.equal(isEligible("/project/deps/first-party.ts", lines(4), policy), true);
  assert.equal(isEligible("/project/external/first-party.ts", lines(4), policy), true);
  assert.equal(isEligible("/project/golden/hand-curated.txt", lines(4), policy), true);
});

test("high-confidence names, paths, and suffixes are excluded", () => {
  for (const path of [
    "/project/package-lock.json",
    "/project/node_modules/a/index.ts",
    "/project/dist/app.js",
    "/project/a.pb.go",
    "/project/db/schema.rb",
    "/project/__snapshots__/a.txt",
  ]) assert.equal(isEligible(path, lines(4), policy), false, path);
  assert.equal(isEligible("/project/types.d.ts", lines(4), policy), true);
  assert.equal(isEligible("/project/custom.lock", lines(4), policy), true);
  assert.equal(isEligible("/project/geography.map", "not json", policy), true);
});

test("generated markers are bounded and ambiguous prose stays eligible", () => {
  const header = `// generated code\n// do not modify\n${lines(4)}`;
  assert.equal(isEligible("/project/a.ts", header, policy), false);
  assert.equal(isEligible("/project/a.ts", `${lines(40)}\n// generated code - do not modify`, policy), true);
  assert.equal(isEligible("/project/readme.md", "Generated code should say do not edit.", policy), true);
  assert.equal(isEligible("/project/readme.md", "// Generated by the protocol buffer compiler", policy), true);
  assert.equal(isEligible("/project/a.js", `${lines(4)}\n//# sourceMappingURL=a.js.map`, policy), false);
  assert.equal(isEligible("/project/a.js", `//# sourceMappingURL=a.js.map\nfirst\nsecond`, policy), true);
  assert.equal(isEligible("/project/a.cs", "[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"tool\", \"1\")]\nclass A {}", policy), false);
  assert.equal(isEligible("/project/a.vb", "<GeneratedCodeAttribute(\"tool\", \"1\")>\nClass A\nEnd Class", policy), false);
});

test("binary is silent unless force-included and source-map JSON is narrow", () => {
  assert.equal(isEligible("/project/a.ts", `a\0b`, policy), false);
  assert.equal(isEligible("/project/image.map", '{"version":3,"sources":[],"mappings":""}', policy), false);
  assert.equal(isEligible("/project/old.map", '{"version":2,"sources":[],"mappings":""}', policy), true);
  assert.equal(isEligible("/project/ambiguous.map", '{"version":3,"sources":[1],"mappings":""}', policy), true);
  assert.equal(isEligible("/project/data.map", '{"version":3,"data":[]}', policy), true);
});
